import sys
from unittest.mock import MagicMock

sys.modules["tvm"] = MagicMock()
sys.modules["tvm.relay"] = MagicMock()
sys.modules["tvm.relay.frontend"] = MagicMock()
sys.modules["tvm.relay.frontend.tensorflow_parser"] = MagicMock()
sys.modules["tvm.relay.testing"] = MagicMock()
sys.modules["tvm.error"] = MagicMock()
sys.modules["treelite"] = MagicMock()
sys.modules["mxnet"] = MagicMock()
sys.modules["xgboost"] = MagicMock()
sys.modules["xgboost.core"] = MagicMock()
sys.modules["torch"] = MagicMock()
sys.modules["torchvision"] = MagicMock()
sys.modules["tensorflow"] = MagicMock()
sys.modules["tensorflow.keras"] = MagicMock()
sys.modules["tensorflow.keras.models"] = MagicMock()
sys.modules["tensorflow.keras.layers"] = MagicMock()
sys.modules["onnx"] = MagicMock()
sys.modules['tvm.autotvm'] = MagicMock()
sys.modules['tvm.autotvm.measure'] = MagicMock()
sys.modules['tvm.autotvm.measure.measure_methods'] = MagicMock()
sys.modules["tflite"] = MagicMock()
sys.modules["tflite.Tensor"] = MagicMock()
sys.modules["tflite.TensorType"] = MagicMock()
sys.modules["tflite.Model"] = MagicMock()
